kind: Template
apiVersion: v1
objects:
- apiVersion: v1
  data:
    bundles.yml: |
      - name: ansible
        skus:
          - RH00798
          - ESA0016
          - MCT3319
          - MCT3319F3
          - MCT3319RN
          - MCT3319S
          - MCT3320
          - MCT3320F3
          - MCT3320RN
          - MCT3320S
          - MCT3321
          - MCT3321F3
          - MCT3321RN
          - MCT3321S
          - MCT3487
          - MCT3487F3
          - MCT3487RN
          - MCT3487S
          - MCT3488
          - MCT3488F3
          - MCT3488RN
          - MCT3488S
          - MCT3685
          - MCT3685RN
          - MCT3685F3
          - MCT3685F3RN
          - MCT3685S
          - MCT3691
          - MCT3691RN
          - MCT3691F3
          - MCT3691F3RN
          - MCT3691S
          - MCT3692
          - MCT3692RN
          - MCT3692F3
          - MCT3692F3RN
          - MCT3692S
          - MCT3693
          - MCT3693RN
          - MCT3693F3
          - MCT3693F3RN
          - MCT3693S
          - MCT3694
          - MCT3694RN
          - MCT3694F3
          - MCT3694F3RN
          - MCT3694S
          - MCT3695
          - MCT3695RN
          - MCT3695F3
          - MCT3695F3RN
          - MCT3695S
          - MCT3696
          - MCT3696RN
          - MCT3696F3
          - MCT3696F3RN
          - MCT3696S
          - MCT3698
          - MCT3698RN
          - MCT3698F3
          - MCT3698F3RN
          - MCT3698S
          - MCT3733
          - MCT3733RN
          - MCT3733F3
          - MCT3733F3RN
          - MCT3733S
          - MCT3734
          - MCT3734RN
          - MCT3734F3
          - MCT3734F3RN
          - MCT3734S
          - MCT3735
          - MCT3735RN
          - MCT3735F3
          - MCT3735F3RN
          - MCT3735S
          - MCT3742
          - MCT3742F3
          - MCT3742RN
          - MCT3742S
          - MCT3743
          - MCT3743F3
          - MCT3743RN
          - MCT3743S
          - MCT3744
          - MCT3744F3
          - MCT3744RN
          - MCT3744S
          - MCT3809
          - MCT3809RN
          - MCT3809F3
          - MCT3809F3RN
          - MCT3809S
          - MCT3810
          - MCT3810RN
          - MCT3810F3
          - MCT3810F3RN
          - MCT3810S
          - MCT3811
          - MCT3811RN
          - MCT3811F3
          - MCT3811F3RN
          - MCT3811S
          - MCT3812
          - MCT3812RN
          - MCT3812F3
          - MCT3812F3RN
          - MCT3812S
          - MCT3813
          - MCT3813RN
          - MCT3813F3
          - MCT3813F3RN
          - MCT3813S
          - MCT3814
          - MCT3814RN
          - MCT3814F3
          - MCT3814F3RN
          - MCT3815S
          - MCT3815
          - MCT3815RN
          - MCT3815F3
          - MCT3815F3RN
          - MCT3816
          - MCT3816RN
          - MCT3816F3
          - MCT3816F3RN
          - MCT3816S
          - MCT3817
          - MCT3817RN
          - MCT3817F3
          - MCT3817F3RN
          - MCT3817S
          - MCT3865
          - MCT3865RN
          - MCT3865F3
          - MCT3865F3RN
          - MCT3865S
          - MCT3866
          - MCT3866RN
          - MCT3866F3
          - MCT3866F3RN
          - MCT3866S
          - MCT3873
          - MCT3873RN
          - MCT3873F3
          - MCT3873F3RN
          - MCT3873S
          - MCT3874
          - MCT3874RN
          - MCT3874F3
          - MCT3874F3RN
          - MCT3874S
          - MCT3875
          - MCT3875RN
          - MCT3875F3
          - MCT3875F3RN
          - MCT3875S
          - MCT3876
          - MCT3876RN
          - MCT3876F3
          - MCT3876F3RN
          - MCT3876S
          - MCT3877
          - MCT3877RN
          - MCT3877F3
          - MCT3877F3RN
          - MCT3877S
          - MCT3878
          - MCT3878RN
          - MCT3878F3
          - MCT3878F3RN
          - MCT3878S
          - MCT3906
          - MCT3906RN
          - MCT3906F3
          - MCT3906F3RN
          - MCT3906S
          - MCT3907
          - MCT3907RN
          - MCT3907F3
          - MCT3907F3RN
          - MCT3907S
          - MCT3908
          - MCT3908RN
          - MCT3908F3
          - MCT3908F3RN
          - MCT3908S
          - MCT3909
          - MCT3909RN
          - MCT3909F3
          - MCT3909F3RN
          - MCT3909S
          - MCT3910
          - MCT3910RN
          - MCT3910F3
          - MCT3910F3RN
          - MCT3910S
          - MCT3911
          - MCT3911RN
          - MCT3911F3
          - MCT3911F3RN
          - MCT3911S
          - MCT3948
          - MCT4249
          - SER0496
          - SER0497
          - SER0569
          - SER0570
          - SER0574
          - MCT3691
          - MCT3692
          - MCT3693
          - MCT3694
          - MCT3695
          - MCT3696
          - MCT4164
          - MCT4165
          - MCT3691F3
          - MCT3692F3
          - MCT3693F3
          - MCT3694F3
          - MCT3695F3
          - MCT3696F3
          - MCT4164F3
          - MCT4165F3
          - MCT3691
          - MCT3692
          - MCT3693
          - MCT3694
          - MCT3695
          - MCT3696
          - MCT4164
          - MCT4165
          - MCT3691F3
          - MCT3692F3
          - MCT3693F3
          - MCT3694F3
          - MCT3695F3
          - MCT3696F3
          - MCT4164F3
          - MCT4165F3

      - name: cost_management
        use_valid_org_id: true

      - name: insights
        use_valid_org_id: true

      - name: migrations
        use_valid_org_id: true

      - name: subscriptions
        use_valid_org_id: true

      - name: settings
        use_valid_org_id: true

      - name: user_preferences
        use_valid_org_id: true

      - name: smart_management
        skus:
          - SVC3124
          - RH00066
          - RH00065
          - RH00798
          - RH00031
          - RH00031F3
          - RH00032
          - RH00032F3
          - RH00039
          - RH00039F3
          - RH00040
          - RH00040F3

      - name: internal
        use_is_internal: true

      - name: rhods
        skus:
          - MCT4217MO
          - MCT4163

      - name: rhoam
        skus:
          - MW01459
          - MW01460
          - MW01461
          - MW01462
          - MW01737
          - MW01458
          - MW01458MO
          - MW01459
          - MW01459MO
          - MW01460
          - MW01460MO
          - MW01461
          - MW01461MO
          - MW01462
          - MW01462MO
          - MW01737
          - MW01738MO
          - MW01845MO
          - MW01846

      - name: rhosak
        skus:
          - MW01882
          - MW01891
          - MW01892MO
          - MW01891
          - MW01892MO
          - MW01894
          - MW01896MO
          - MW01893
          - MW01895MO
 
      - name: openshift 
        skus:
          - MW00454
          - MW00457F3RN
          - MW00454F3RN
          - MW00454RN
          - MW00457RN
          - MW00457
          - MW00454F3
          - MW00457F3
          - MW00455F3RN
          - MW00455
          - MW00458F3
          - MW00455RN
          - MW00448F3
          - MW00452
          - MW00449S
          - MW00451
          - MW00682
          - MW00451RN
          - MW00371
          - MW00452S
          - MW00451F3
          - MW00449F3
          - MW00452F3
          - MW00991
          - MW00683
          - MW00449
          - MW00450
          - MW00453
          - MW00453F3
          - MW00450F3
          - MW00448
          - MW00448S
          - MW00450RN
          - MW00452RN
          - MW00453S
          - MW00453RN
          - MW00449RN
          - MW00368
          - MW00370F3
          - MW00448F3RN
          - MW00370
          - MW00682MO
          - MW00368F3
          - MW00367F3
          - MW00367
          - MW00460
          - MW00448RN
          - MW00369
          - MW00992
          - MW00450S
          - MW00992RN
          - MW00684
          - MW00371F3
          - MW00451S
          - MW00449F3RN
          - MW00452F3RN
          - MW00463
          - MW00451F3RN
          - MW00461
          - MW00464
          - MW00993
          - MW00376RN
          - MW00377RN
          - MW00374RN
          - MW00688F3
          - MW00375
          - MW00373F3RN
          - MW00378
          - MW00999
          - MW00374S
          - MW00373F3
          - MW00376
          - MW00374
          - MW00373RN
          - MW00997
          - MW00377F3RN
          - MW00376S
          - MW00999RN
          - MW00375RN
          - MW00391
          - MW00393
          - MW00377S
          - MW00377
          - MW00378F3
          - MW00373S
          - MW00374F3
          - MW00392
          - MW00998
          - MW00378RN
          - MW00377F3
          - MW00373
          - MW00376F3
          - MW00375F3
          - MW00376F3RN
          - MW00366
          - MW00362RN
          - MW00365RN
          - MW00365
          - MW00364S
          - MW00365S
          - MW00362F3
          - MW00361RN
          - MW00366F3
          - MW01004
          - MW00382
          - MW00363
          - MW00364
          - MW00364F3
          - MW00681
          - MW00362S
          - MW00362
          - MW00361
          - MW00361S
          - MW00364RN
          - MW00361F3
          - MW00366RN
          - MW00384F3
          - MW00363S
          - MW01002
          - MW00361F3RN
          - MW00382F3
          - MW00362F3RN
          - MW00364F3RN
          - MW00365F3
          - MW00363RN
          - MW00679MO
          - MW00380
          - MW00379RN
          - MW01007
          - MW01003
          - MW01003RN
          - MW00366S
          - MW00680
          - MW00363F3RN
          - MW01006
          - MW00679
          - MW00363F3
          - MW00379
          - MW00383F3
          - MW00381
          - MW00365F3RN
          - MW01007RN
          - MW01257
          - MW01255
          - MW01329RN
          - MW01258
          - MW01254
          - MW01257F3
          - MW01254F3
          - MW01329
          - MW01263
          - MW01286
          - MW01260
          - MW01267
          - MW01270
          - MW01266
          - MW01271
          - MW01268
          - MW01269
          - MCT3009
          - MW01008
          - MW00329RN
          - MCT3265
          - MCT2735F3RN
          - MCT3016
          - MW00330
          - MW00329F3
          - MW00329
          - MW00594HR
          - MW00331F3
          - ESA0012
          - MCT2863
          - MW01382
          - MW01502
          - MCT3264
          - MCT2862F3
          - MW00330RN
          - MW00210HR
          - MCT3266
          - MCT3756
          - MCT2862S
          - MCT3156
          - MCT3753
          - MCT3753F3
          - MW00211HR
          - MCT3263
          - MCT2863F3
          - MW00227
          - MW00332
          - MW00332F3
          - MCT3754
          - MW01009
          - MW01463F3
          - MCT3479F3
          - MW00421RN
          - MCT2736
          - MW00226
          - MCT2735S
          - MCT2735RN
          - MCT3010
          - MCT3754F3
          - MCT3268
          - MCT3818
          - MCT2863RN
          - MCT2735F3
          - MCT2736F3
          - MW00226MO
          - MCT2862RN
          - MCT2736RN
          - MCT2862
          - MW00331
          - MCT2736S
          - MW00335
          - MW00472F3
          - MCT3819F5
          - MCT2735
          - MW00330F3
          - MW00330S
          - MCT3760F3
          - MW00422
          - MW01743
          - MCT2863S
          - MW00329F3RN
          - MW00331RN
          - MW00421F3
          - MW01744
          - MW01501F3
          - MW01502F3
          - MW01246
          - MW01739
          - MCT3755
          - MCT3479
          - MW00421
          - MW00335RN
          - MW01383
          - MCT3579RN
          - MW00419F3
          - MCT3579
          - MW01247
          - MW00332RN
          - MCT3760
          - MCT3478S
          - MW00332S
          - SER0423
          - MW01615
          - MW00595
          - MCT3479S
          - MCT2862F3RN
          - MCT2738
          - MW00227F3
          - MW00501
          - MW01320
          - MCT3477F3
          - MW00785F3
          - MW00782F3
          - MCT3478F3RN
          - MCT3754S
          - MW01965
          - MCT3754RN
          - MCT3489S
          - MW02031MO
          - MW01951MO
          - SER0620
          - MW01482F3
          - MW01853
          - MW00334
          - MW02055
          - MCT3754F3RN
          - MW00210MO
          - MCT3477RN
          - MCT3753RN
          - MCT3753F3RN
          - MCT3492
          - MCT3491
          - MCT2863F3RN
          - MCT3156RN
          - MCT3477
          - MCT3818F3
          - MW01849
          - MW01482
          - MCT3819
          - MW01501
          - MCT3581RN
          - MW00782
          - MW00331S
          - MCT3819F3
          - MW00336
          - MW00331F3RN
          - MW01465F3
          - MW01309
          - MW01463
          - MW00783F3
          - MCT3819S
          - MCT3580
          - MW00422F5
          - MW01740
          - MW02045HR
          - MCT3489
          - MCT2658
          - MW01245
          - MCT3758
          - MW01615F3
          - MW01382S
          - MW00333
          - MW00329S
          - MW00472
          - MW00419
          - MW01009RN
          - MW01950MO
          - MW00330F3RN
          - MW00226F3
          - MW01741
          - MCT2956
          - MCT3820
          - MCT3478
          - MCT3478F3
          - MCT3581F3
          - MW01018
          - MW01742
          - MCT2737
          - MCT3479RN
          - MW00336RN
          - MW01507
          - MW00421F5
          - MW01316
          - MCT3759
          - MW01398
          - MCT3580RN
          - MW01019
          - MW01008RN
          - MCT3581
          - MCT3490
          - MCT3476F3
          - ESA0019
          - MW01507F3
          - MW01988
          - MCT2736F3RN
          - MW00783
          - MW00422F3
          - MCT3818F5
          - MW01241HR
          - MCT3478RN
          - MW00419F5
          - MW00788
 
      - name: rhel
        skus:
          - RH00732
          - RH00030
          - RH00038
          - RH00754
          - RH00506
          - RH00508
          - RH00518
          - RH00519
          - RH01934
          - RH00061
          - RH00064
          - RH00025
          - RH00033
          - RH00743
          - RH00744
          - RH01936
          - RH00059
          - RH00062
          - RH2262474
          - RH2264664
          - RH2282403
          - RH3413336
          - RH3482727
          - RH00270
          - RH00271
          - RH00003
          - RH00004
          - RH00432
          - RH00433
          - RH00013
          - RH00014
          - RH00005
          - RH00015
          - RH00010
          - RH00020
          - RH02572
          - RH02584
          - RH02577
          - RH02578
          - RH00434
          - RH00435
          - RH00584
          - RH00585
          - RH00559
          - RH02566
          - RH02567
          - RH00575
          - RH00561
          - RH00592
          - RH00560
          - RH00583
          - RH00555
          - RH00556
          - RH02573
          - RH02579
          - RH02580
          - RH02585
          - RH00573
          - RH00574
          - RH00557
          - RH00558
          - RH02574
          - RH02575
          - RH02576
          - RH02586
          - RH00586
          - RH00587
          - RH00008
          - RH00009
          - RH00023
          - RH00024
          - RH00018
          - RH00019
          - RH0923296
          - RH0958488
          - RH0981731
          - RH0986300
          - RH0990680
          - RH00817
          - RH00816
          - RH00814
          - RH00815
          - RH00810
          - RH00811
          - RH00812
          - RH00813
          - RH02210 
          - RH00276
          - RH00277
          - RH00284
          - RH00285
          - RH00286
          - RH00287
          - RH01910
          - RH01911
          - RH01912
          - RH01913
          - RH00150
          - RH00151
          - RH00158
          - RH00159
          - RH02212
          - RH00640
          - RH00641
          - RH00656
          - RH00657
          - RH01922
          - RH01923
          - RH00148
          - RH00149
          - RH00156
          - RH00157
          - RH00152
          - RH00153
          - RH00763
          - RH00764
          - RH00759
          - RH00760
          - RH00001
          - RH00002
          - RH00011
          - RH00012
          - RH00767
          - RH00768
          - RH00006
          - RH00007
          - RH00021
          - RH00022
          - RH00016
          - RH00017
          - RH00154
          - RH00155
          - RH00162
          - RH00163
          - RH00642
          - RH00643
          - RH01924
          - RH01925
          - RH00160
          - RH00161
          - RH00026
          - RH00034
          - RH00749
          - RH00750
          - RH01938
          - RH00060
          - RH00063
          - RH00031
          - RH00039
          - RH00032
          - RH00040

  kind: ConfigMap
  metadata:
    creationTimestamp: null
    name: entitlements-config
    annotations:
      qontract.recycle: "true"